### ISSUE TITLE
Term "invoice" is not clear

### ISSUE THREAD

**Issue by DronMDF** [zold-io/papers#10]
Invoice - this is a part of score prefix.
How score(invoice) corellate with wallets/transactions?

In 8th part score used for select right wallet.
Invoice is wallet id?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB08FTCNQ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@yegor256 in the whitepaper, the term `invoice`, outside of its introduction as a term, is only ever used when describing how taxes are paid, but even there it's meaning or purpose is unclear:

> In order to pay taxes the owner of the wallet must select a remote node from
the network with a score of 16 or more.  Then, it has to take the invoice
from the score, request the node to lock the score for a minute, and send the
payment of 1 ZLD or less to that node.  The score with exactly 16 suffixes
has to be placed into the details of the transaction, prefixed by
TAXES.

"Take invoice from the score" and then what does the node do with it?

**Comment by 0crat** [comment]
The job [#10](https://github.com/zold-io/papers/issues/10) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB08FTCNQ/1780741473); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#10` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dronmdf[/z](https://www.0crat.com/u/dronmdf)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@llorllale @DronMDF I believe it's fixed in ed298e4 Thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.5`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#10](https://github.com/zold-io/papers/issues/10) is now out of scope
