### ISSUE TITLE
RESTful API 'version' and 'X-Zold-Version' is zold locked

### ISSUE THREAD

**Issue by DronMDF** [zold-io/papers#13]
Node can use alternative implementations, and software version сan be very different.

It would be correct to use the protocol version.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB08FTCNQ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@DronMDF maybe we will just add a new header `X-Zold-Protocol` and `protocol` JSON element. WDYT?

**Comment by DronMDF** [comment]
@yegor256 Yes, I think the software version is information. There may be alternative implementations. And updating the software is not always an occasion to update the entire network of nodes. The protocol of interaction varies comparatively rarely.

I like X-Zold-Protocol as a strict requirement.
X-Zold-Version for info.

**Comment by 0crat** [comment]
The job [#13](https://github.com/zold-io/papers/issues/13) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB08FTCNQ/1781355667); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#13` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dronmdf[/z](https://www.0crat.com/u/dronmdf)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@DronMDF fixed in f5561d9 thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#13](https://github.com/zold-io/papers/issues/13) is now out of scope
