### ISSUE TITLE
Home page does not contain score time

### ISSUE THREAD

**Issue by DronMDF** [zold-io/papers#14]
```
{
  "version": "0.6.1" ,
  "score": {
    "value": 3,
    "host": "b2.zold.io" ,
    "port": 4096,
    "invoice": "THdonv1E@0000000000000000" ,
    "suffixes": [ "4f9c38" , "49c074" , "24829a" ],
    "strength": 6
  }
}
```
What makes it impossible to check the score.
Node can publish fake score.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB08FTCNQ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#14` is not assigned, can't get performer
