### ISSUE TITLE
more details

### ISSUE THREAD

**Issue by yegor256** [zold-io/papers#23]
Let's add more details here and there

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#23` is not assigned, can't get performer
