### ISSUE TITLE
Whitepaper Should Have More Info On Zold Supply

### ISSUE THREAD

**Issue by Wysie** [zold-io/papers#25]
I noticed zold.io talks briefly about total supply ("The technical cap of the currency is 2.15b ZLD. There is a formula that restricts the speed of emission, allowing no greater than 50% of the total capacity to be issued before May, 2021; the remaining 50% can be issued before the end of 2028") but whitepaper doesn't really touch on this point other than the "Mining Formula" section.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@e20dfc0e-2ccc-4a5c-9ba0-ccd6afb8ff27, thread: pool-19-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "catalog.xml" in "PMO" in 1min: ffe0265a2bf5/24min/0/1/true/false by AsyncFlush-7
```

[0.22.15](https://github.com/zerocracy/farm): Issue: zold-io/papers#25, Action: `opened`

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by yegor256** [comment]
@Wysie check version 0.2.0 please: https://papers.zold.io/wp.pdf I added the section "Total Supply" it briefly explains what's going on. Do you think this is enough?

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#25` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
