### ISSUE TITLE
proof of work - which data is used

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/papers#27]
It isn't clear which input will be taken for the proof of work `sha256` calculations.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB08FTCNQ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#27](https://github.com/zold-io/papers/issues/27) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CB08FTCNQ/1780645952); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#27` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@oltdaniel you are right, there were mistakes in the documentation. See the fix in d8cb99c Thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.4`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#27](https://github.com/zold-io/papers/issues/27) is now out of scope
