### ISSUE TITLE
Not clear what should be hashed 

### ISSUE THREAD

**Issue by ajdevy** [zold-io/papers#3]
On page 5 of the white paper it is written:
"Then, the node attempts to append any arbitrary **_text_**, which has to match
/[a-zA-Z0-9]+/ regular expression, to the end of the prefix and calculates
SHA-256 hash of the _**text**_ in the hexadecimal format. For example, this
would be the prefix with the attached 16bda66 suffix:"

It is not clear which text should be hashed, the whole string or only the arbitrary part. From the context, the word "text" relates to the arbitrary text.
Nevertheless even the whole string produces a different hash, as calculated here http://passwordsgenerator.net/sha256-hash-generator/
"2018-05-17T03:50:59Z b2.zold.io 4096 THdonv1E@abcdabcdabcdabcd 16bda66"
produces "32305E21903701736687240A8760FF2A7125CA9343B50292D42AC387FF6DAD03"

**Comment by yegor256** [comment]
@ajdevy it's all fixed now, please check the latest version of WP

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#3` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
