### ISSUE TITLE
add LaTeX packages to the build

### ISSUE THREAD

**Issue by yegor256** [zold-io/papers#37]
Let's put them in

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.4`

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#37` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
