### ISSUE TITLE
green paper russian

### ISSUE THREAD

**Issue by yegor256** [zold-io/papers#39]
Let's translate

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#39` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
