### ISSUE TITLE
Tailing zeros explanation in white paper

### ISSUE THREAD

**Issue by ajdevy** [zold-io/papers#4]
1) In the white paper page 6 it is stated that the node attempts to find a hash with "few tailing zeros", and the first one is with 7 tailing zeros, but in the white paper it is stated that there are 6 tailing zeros.
2) It is unclear if the next hash has to have to same amount of tailing zeros as it's predecessor
3) It is unclear what is the minimal amount of tailing zeros, 2?

**Comment by yegor256** [comment]
@ajdevy I believe current version of the WP explains it all. If not, feel free to open a new ticket.

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#4` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
