### ISSUE TITLE
thumbs

### ISSUE THREAD

**Issue by yegor256** [zold-io/papers#48]

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.3`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#48` is not assigned, can't get performer
