### ISSUE TITLE
Why is max per trx for Tax 1 Zold?

### ISSUE THREAD

**Issue by llorllale** [zold-io/papers#49]
Why is the maximum amount per transaction for tax payment set to 1 Zold?

> In order to pay taxes the owner of the wallet must select a remote node from
the network with a score of 16 or more.  Then, it has to take the invoice
from the score, request the node to lock the score for a minute, and **send the
payment of 1 ZLD or less** to that node.  The score with exactly 16 suffixes
has to be placed into the details of the transaction, prefixed by
TAXES

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB08FTCNQ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@llorllale to ensure that tax payments are distributed more or less equally between nodes

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#49` is not assigned, can't get performer
