### ISSUE TITLE
Unclear metrics of CPU power

### ISSUE THREAD

**Issue by ajdevy** [zold-io/papers#5]
"The strength of the score is the amount of the trailing zeros in the hash."  - is it assumed that the more tailing zeros you can find, the more CPU power you have?

**Comment by yegor256** [comment]
@ajdevy explained in 0a4b24a thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#5` is not assigned, can't get performer
