### ISSUE TITLE
Unclear motivation of why a transactions Id should point to a beneficiaries wallet ID 

### ISSUE THREAD

**Issue by ajdevy** [zold-io/papers#6]
"Transactions with positive amount don’t have signatures. Their IDs point to ID fields of corresponding beneficiaries’ wallets."

**Comment by yegor256** [comment]
@ajdevy it seems that we may get rid of transaction IDs at all, let's continue in #19

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#6` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
