### ISSUE TITLE
freelance deck

### ISSUE THREAD

**Issue by yegor256** [zold-io/papers#64]

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#64` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
