### ISSUE TITLE
feature deck

### ISSUE THREAD

**Issue by yegor256** [zold-io/papers#66]
Let's list all Zerocracy features

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#66` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
