### ISSUE TITLE
We can’t believe to current timestamp parsed from score of external node

### ISSUE THREAD

**Issue by dapi** [zold-io/papers#68]
That is why we can’t decide is score still alive or not and can’t really know how long has it been calculating.

Possible solution is to have something `trusted network time`, to compare received score time with it.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB08FTCNQ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi can you please explain what exactly will be done by the fraudulent node in order to compromise our protocol?

**Comment by dapi** [comment]
Change node’s local time into the future and spend whole time of shifted period to calculate score’s value instead of expected 24 hours.

**Comment by yegor256** [comment]
@dapi I quote the White Paper: "The score is only valid when the starting time is earlier than
the current time, but not earlier than 24 hours ago." Thus, every client, which will see your score, will just ignore it as "invalid" if your time is ahead in the future, comparing to the local time _of the client_.

**Comment by yegor256** [comment]
@dapi This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#68` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by dapi** [comment]
> This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

I'm not sure. I believe you must not use timestamp  to check or trust given score in any cases.
