### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by alex-semenyuk** [zold-io/papers#7]
Page 3 (twice Plancoin)

Similar to many other digital currencies—including Bitcoin,Etherium, **Plancoin**, Monero, Trinity, **Plancoin**, Dero, and many others—Zold nodes find consensus by comparing the amount of CPU power invested by
each of them into finding hash suffixes, performing certain expensive and meaningless calculations

**Comment by yegor256** [comment]
@alex-semenyuk please, submit a pull request

**Comment by yegor256** [comment]
@alex-semenyuk thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#7` is not assigned, can't get performer
