### ISSUE TITLE
gazeta

### ISSUE THREAD

**Issue by yegor256** [zold-io/papers#82]

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by 0crat** [comment]
Job `gh:zold-io/papers#82` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
